// This file is automatically generated. Do not edit.
export const firebaseConfig = {
  projectId: 'studio-454255037-163c0',
  appId: '1:245763967149:web:9a79ec102546e386aa9e24',
  apiKey: 'AIzaSyDagpmm8gHroAn6RY_nur2YTYJCDWeVDXE',
  authDomain: 'studio-454255037-163c0.firebaseapp.com',
  storageBucket: 'studio-454255037-163c0.appspot.com',
  messagingSenderId: '245763967149',
  measurementId: 'G-D1Y2X3B4E5',
};
